# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: JRTP701-MiniProj01-CURDOperations
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: nitraja
    password: nitraja
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 4041

plan:
 module:
  messages:
    save-success: Travel Plan is saved with id value
    save-failure: Travel Plan is not saved with id value
    find-by-id-failure: Travel Plan is not found
    update-success: TravelPlan is updated
    update-failure: TravelPlan is not found for updation
    delete-success: TravelPlan is deleted
    delete-failure: TravelPlan is not found for deletion
    status-change-success: Travel Plan status is changed
    status-change-failure: Travel Plan is not found for status change
